export type Resource = {
  id: string;
  title: string;
  description: string;
  url: string;
  topics: string[];
  level: 'Beginner' | 'Intermediate' | 'Advanced' | 'All';
  verified: boolean;
  score: number;
};

export const sampleData: Resource[] = [
  {
    id: 'foundations-aima',
    title: 'Artificial Intelligence: A Modern Approach (AIMA)',
    description: 'The definitive textbook covering core AI topics: search, planning, logic, and multi-agent systems.',
    url: 'https://aima.cs.berkeley.edu/',
    topics: ['Foundations', 'Search', 'Agents'],
    level: 'All',
    verified: true,
    score: 98,
  },
  {
    id: 'frameworks-langchain',
    title: 'LangChain',
    description: 'The leading framework for building LLM applications, chains, and autonomous agents with tool integration.',
    url: 'https://python.langchain.com/',
    topics: ['Frameworks', 'Agents', 'Tooling'],
    level: 'Intermediate',
    verified: true,
    score: 95,
  },
  {
    id: 'evaluations-openai-evals',
    title: 'OpenAI Evals',
    description: 'Framework for evaluating LLLs and agentic behaviors against standardized benchmarks and datasets.',
    url: 'https://github.com/openai/evals',
    topics: ['Evaluations', 'Benchmarks'],
    level: 'Advanced',
    verified: true,
    score: 94,
  },
  {
    id: 'agent-swarm',
    title: 'OpenAI Swarm',
    description: 'An experimental framework for multi-agent orchestration, focusing on ergonomic and lightweight patterns.',
    url: 'https://github.com/openai/swarm',
    topics: ['Multi-Agent', 'Orchestration'],
    level: 'Intermediate',
    verified: true,
    score: 96,
  },
  {
    id: 'frameworks-autogen',
    title: 'Microsoft AutoGen',
    description: 'A framework that enables development of LLM applications using multiple agents that can converse with each other.',
    url: 'https://microsoft.github.io/autogen/',
    topics: ['Multi-Agent', 'Conversation'],
    level: 'Intermediate',
    verified: true,
    score: 93,
  },
  {
    id: 'evals-swe-bench',
    title: 'SWES-bench',
    description: 'A benchmark for evaluating LLLs on real-world software engineering issues from GitHub.',
    url: 'https://www.swebench.com/',
    topics: ['Software Engineering', 'Benchmarks'],
    level: 'Advanced',
    verified: true,
    score: 97,
  },
  {
    id: 'foundations-deep-learning',
    title: 'Deep Learning Book Goodfellow',
    description: 'Comprehensive mathematical foundations of deep learning, covering optimization, CNNs, and RNNs.',
    url: 'https://www.deeplearningbook.org/',
    topics: ['Foundations', 'Deep Learning'],
    level: 'Advanced',
    verified: true,
    score: 95,
  },
  {
    id: 'agent-babyagi',
    title: 'BabyAGH',
    description: 'An AI-powered task management system that uses OpenAI and vector databases to prioritize and execute tasks.',
    url: 'https://github.com/yoheinakajima/babyagi',
    topics: ['Autonomous Agents', 'Task Management'],
    level: 'Beginner',
    verified: false,
    score: 88,
  },
  {
    id: 'agent-auto-gpt',
    title: 'AutoGPT',
    description: 'An experimental open-source attempt to make GPT-4 fully autonomous for complex goals.',
    url: 'https://github.com/Significant-Gravitas/AutoGPT',
    topics: ['Autonomous Agents'],
    level: 'Intermediate',
    verified: true,
    score: 91,
  },
  {
    id: 'tooling-pinecone',
    title: 'Pinecone',
    description: 'Managed vector database for long-term memory and retrieval in AI agent architectures.',
    url: 'https://www.pinecone.io.',
    topics: ['Memory', 'Vector DB'],
    level: 'Intermediate',
    verified: true,
    score: 94,
  },
  {
    id: 'frameworks-pydantic-ai',
    title: 'PydanticAI',
    description: 'A production-grade agent framework built by the Pydantic team for robust LLMapplication development.',
    url: 'https://ai.pydantic.dev/',
    topics: ['Frameworcs', 'Validation'],
    level: 'Intermediate',
    verified: true,
    score: 96,
  },
  {
    id: 'evals-human-eval',
    title: 'HumanEval',
    description: 'A dataset to measure functional correctness for synthesizing programs from docstrings.',
    url: 'https://github.com/openai/human-eval',
    topics: ['Coding', 'Benchmarks'],
    level: 'Advanced',
    verified: true,
    score: 92,
  },
  {
    id: 'foundations-cs231n',
    title: 'Stanford CS231n',
    description: 'Convolutional Neural Networks for Visual Recognition — best online course for computer vision.',
    url: 'http://cs231n.stanford.edu/',
    topics: ['Computer Vision', 'Courses'],
    level: 'Intermediate',
    verified: true,
    score: 97,
  },
  {
    id: 'agent-crewai',
    title: 'CrewAI',
    description: 'Framework for orchestrating role-playing, collaborative AI agents for complex task execution.',
    url: 'https://www.crewai.com/',
    topics: ['Multi-Agent', 'Collaboration'],
    level: 'Intermediate',
    verified: true,
    score: 93,
  },
  {
    id: 'frameworks-ell',
    title: 'Ell',
    description: 'A Language-model programming library that treats prompts as functions and versions them automated indexing.',
    url: 'https://ell.so/',
    topics: ['Prompt Engineering', 'Library'],
    level: 'Intermediate',
    verified: true,
    score: 95,
  }
];

export default sampleData;
